<div class="row ">
    <div class="col-xs-12 col-sm-12 col-md-8 col-md-offset-2">
        <form class="form-horizontal" role="form">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="form-group">
                        <label for="word" class="col-lg-3 control-label">Word</label>

                        <div class="col-lg-7">
                            <input type="text" class="form-control input-lg" id="word"
                                   placeholder="Please input your word">
                        </div>
                    </div>

                    <div class="form-group">
                        <ul class="col-lg-offset-3">
                            <li >
                                    <b>Hello</b>
                                    <i>greeting</i>
                                    <button type="button" class="btn  btn-default btn-sm ">
                                        <span class="glyphicon glyphicon-pencil"></span>
                                    </button>
                            </li>
                            <li>
                                <b >Hello</b>
                                <i>greeting</i>
                                <button type="button" class="btn  btn-default btn-sm ">
                                    <span class="glyphicon glyphicon-pencil"></span>
                                </button>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="form-group">
                        <label for="tags" class="col-lg-3 control-label">Tags</label>

                        <div class="col-lg-7">
                            <input type="text" class="form-control input-lg" id="tags" placeholder="">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="isToiec" class="col-lg-3 control-label">TOIEC Word</label>

                        <div class="col-lg-7">
                            <div class="checkbox">
                                <input type="checkbox" id="isToiec">
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <ul class="nav nav-tabs" id="myTab">
                <li class="active"><a href="#en">English</a></li>
                <li><a href="#vn">Vietnamese</a></li>
            </ul>
            <br/>

            <div class="tab-content">
                <!-- tab EN content -->
                <div class="tab-pane active" id="en">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div class="form-group">
                                <label for="inputEmail1" class="col-lg-3 control-label">Sentence #1</label>

                                <div class="col-lg-7">
                                    <input type="email" class="form-control" id="inputEmail1">
                                </div>
                                <div class="col-lg-2">
                                    <button type="button" class="btn  btn-default ">
                                        <span class="glyphicon glyphicon-remove"></span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-offset-3 col-lg-9">
                            <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-plus"></span>
                                Sentence
                            </button>
                        </div>
                    </div>
                    <hr>
                    <div class="panel panel-default">
                        <div class="panel-body">


                            <div class="form-group">
                                <label for="inputPassword1" class="col-lg-3 control-label">English Meaning</label>

                                <div class="col-lg-7">
                                    <textarea placeholder="Hello: meaning" class="form-control"></textarea>
                                </div>
                                <div class="col-lg-2">
                                </div>
                            </div>


                        </div>
                    </div>
                </div>
                <!-- end tab EN content -->

                <!-- tab VI content -->
                <div class="tab-pane " id="vn">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div class="form-group has-warning">
                                <label for="inputEmail1" class="col-lg-3 control-label">Sentence #1</label>

                                <div class="col-lg-7">
                                    <input type="email" class="form-control" id="inputEmail1" placeholder="">

                                </div>
                                <div class="col-lg-2">
                                    <button type="button" class="btn  btn-default ">
                                        <span class="glyphicon glyphicon-remove"></span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-offset-3 col-lg-9">
                            <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-plus"></span>
                                Sentence
                            </button>
                        </div>
                    </div>
                    <hr>
                    <div class="panel panel-default">
                        <div class="panel-body">


                            <div class="form-group">
                                <label for="inputPassword1" class="col-lg-3 control-label">Vietnam Meaning</label>

                                <div class="col-lg-7">
                                    <textarea placeholder="Hello: meaning" class="form-control"></textarea>
                                </div>
                                <div class="col-lg-2">
                                </div>
                            </div>


                        </div>
                    </div>
                </div>
                <!-- end tab VI content -->

            </div>

            <!-- save , clear button -->
            <div class="form-group">
                <div class="col-lg-offset-3 col-lg-9">
                    <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-disk"></span>
                        Add
                    </button>
                    <button type="submit" class="btn btn-default">Clear</button>
                </div>
            </div>


        </form>


    </div>

</div>