<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-8 col-md-offset-2">
        <form class="form-horizontal" method="post" action="" id="add-word-form">
            <div class="error-message">

            </div>

            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="form-group">
                        <label for="word" class="col-lg-3 control-label">Word</label>
                        <div class="col-lg-7">
                            <input type="text" class="form-control input-lg" id="word" name="word" autocomplete="off"
                                   placeholder="Please input your word" onchange="checkExistWord()">
                        </div>
                    </div>

                    <div class="form-group">
                        <ul id="existWordList" class="col-lg-offset-3">
                        </ul>
                    </div>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="form-group">
                        <label for="txtTags" class="col-lg-3 control-label">Tags</label>
                        <div class="col-lg-7">
                            <input type="text" class="form-control" id="txtTags" name="txtTags" value="">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="isToiec" class="col-lg-3 control-label">TOEIC Word</label>
                        <div class="col-lg-7">
                            <div class="checkbox">
                                <input type="checkbox" id="isToeic" name="isToeic" value="0">
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <ul class="nav nav-tabs" id="myTab">
                <li class="active"><a href="#en">English</a></li>
                <li><a href="#vn">Vietnamese</a></li>
            </ul>
            <br/>

            <div class="tab-content">
                <!-- tab EN content -->
                <div class="tab-pane active" id="en">
                    <div class="panel panel-default">
                        <div class="panel-body" id="en-sentence-container">

                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-offset-3 col-lg-9">
                            <button type="button" class="btn btn-default add-sentence">
                                <span class="glyphicon glyphicon-plus"></span>
                                Sentence
                            </button>
                        </div>
                    </div>
                    <hr>
                    <div class="panel panel-default">
                        <div class="panel-body">


                            <div class="form-group">
                                <label for="en-meaning" class="col-lg-3 control-label">English Meaning</label>
                                <div class="col-lg-7">
                                    <textarea class="form-control" id="en-meaning" name="en-meaning" rows="5"></textarea>
                                </div>
                                <div class="col-lg-2">
                                </div>
                            </div>


                        </div>
                    </div>
                </div>
                <!-- end tab EN content -->

                <!-- tab VI content -->
                <div class="tab-pane " id="vn">
                    <div class="panel panel-default">
                        <div class="panel-body" id="vi-sentence-container">

                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-offset-3 col-lg-9">
                            <button type="button" class="btn btn-default add-sentence">
                                <span class="glyphicon glyphicon-plus"></span>
                                Sentence
                            </button>
                        </div>
                    </div>
                    <hr>
                    <div class="panel panel-default">
                        <div class="panel-body">


                            <div class="form-group">
                                <label for="vi-meaning" class="col-lg-3 control-label">Vietnam Meaning</label>

                                <div class="col-lg-7">
                                    <textarea class="form-control" id="vi-meaning" name="vi-meaning" rows="5"></textarea>
                                </div>
                                <div class="col-lg-2">
                                </div>
                            </div>


                        </div>
                    </div>
                </div>
                <!-- end tab VI content -->

            </div>

            <!-- save , clear button -->
            <div class="form-group">
                <div class="col-lg-offset-3 col-lg-9">
                    <button type="button" class="btn btn-primary btn-addWord">
                        <span class="glyphicon glyphicon-floppy-disk"></span>
                        Add
                    </button>
                    <button type="reset" class="btn btn-default">Clear</button>
                </div>
            </div>

        </form>
    </div>
</div>

<script type="text/javascript" src="/js/addform.js"></script>