<input type="hidden" value="<?php echo $data['Word']->WordId; ?>" name="wordId" />
<div class="panel panel-default">
    <div class="panel-body">
        <div class="form-group">
            <label for="txtWord" class="col-lg-3 control-label">Word</label>
            <div class="col-lg-7">
                <input type="text" class="form-control input-lg" id="txtWord" name="txtWord" value="<?php echo $data['Word']->Word; ?>">
            </div>
        </div>
        <div class="form-group">
            <label for="txtTags" class="col-lg-3 control-label">Tags</label>
            <div class="col-lg-7">
                <input type="text" class="form-control" id="txtTags" name="txtTags" value="">
            </div>
        </div>
        <div class="form-group">
            <label for="isToeic" class="col-lg-3 control-label">TOEIC Word</label>
            <div class="col-lg-7">
                <input type="checkbox" id="isToeic" name="isToeic" <?php echo ($data['Word']->IsToeic)? 'checked="true"' : ''; ?>>
            </div>
        </div>

        <!--<div class="form-group">
            <label for="inputEmail1" class="col-lg-3 control-label">US, Male</label>
            <div class="col-lg-9">
                <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-volume-up"></span></button>
                <button type="button" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span></button>
                <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-remove"></span></button>
            </div>
        </div>

        <div class="form-group">
            <label for="inputEmail1" class="col-lg-3 control-label">Voice File</label>
            <div class="col-lg-3 ">
                <select class="form-control ">
                    <option>US, Male</option>
                    <option>US, Female</option>
                </select>
            </div>

            <div class="col-lg-4 ">
                <input type="file" class="form-control " id="inputEmail1">
            </div>

            <div class="col-lg-2">
                <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-open"></span> Upload</button>
            </div>
        </div>

        <hr>
        <div class="form-group">
            <div class="col-lg-offset-3 col-lg-9">
                <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-plus"></span> Voice</button>
            </div>
        </div>-->
    </div>
</div>

<ul class="nav nav-tabs" id="myTab">
    <li class="active"><a href="#en" id="tabEN">English (5/6)</a></li>
    <li class=""><a href="#vn" id="tabVI">Vietnamese (3/6)</a></li>
</ul>

<br>
<div class="tab-content">
    <!-- tab EN content -->
    <div class="tab-pane active" id="en">
        <div class="panel panel-default">
            <div class="panel-body">
                <div id="sentencesEN">
                    <?php $nApprovedEN = 0; $nTotalEN = 0; ?>
                    <?php $i=1; foreach($data['SentenceEN'] as $sentence) : ?>
                    <?php $nApprovedEN = $nApprovedEN + (($sentence->IsApproved) ? 1 : 0); ?>
                    <div class="form-group" id="sentenceEN-<?php echo $i; ?>">
                        <input type="hidden" name="id-sentencesEN[]" value="<?php echo $sentence->SentenceId; ?>">
                        <label for="sentenceEN-<?php echo $i; ?>" class="col-lg-3 control-label">Sentence #<?php echo $i; ?></label>
                        <div class="col-lg-7">
                            <input type="text" name="content-sentencesEN[]" class="form-control" id="sentenceEN-<?php echo $i; ?>" value="<?php echo $sentence->Sentence; ?>">
                        </div>
                        <div class="col-lg-2">
                            <button type="button" class="btn <?php echo ($sentence->IsApproved) ? 'btn-success' : 'btn-default' ?>"
                                    onclick="approveSentence(<?php echo $sentence->SentenceId; ?>, 'EN')" id="btnSentence<?php echo $sentence->SentenceId; ?>">
                                <span class="glyphicon glyphicon-ok"></span>
                            </button>
                            <?php if($i > 1): ?>
                            <button type="button" class="btn btn-default" onclick="ajaxDeleteSentence(<?php echo $i; ?>, <?php echo $sentence->SentenceId; ?>)">
                                <span class="glyphicon glyphicon-remove"></span>
                            </button>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php $i++; endforeach; $nTotalEN=$i-1;?>
                </div>

                <!--<div class="form-group">
                    <label for="inputEmail1" class="col-lg-3 control-label">US, Male</label>
                    <div class="col-lg-9">
                        <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-volume-up"></span></button>
                        <button type="button" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span></button>
                        <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-remove"></span></button>
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputEmail1" class="col-lg-3 control-label">Voice File</label>
                    <div class="col-lg-3 ">
                        <select class="form-control ">
                            <option>US, Male</option>
                            <option>US, Female</option>
                        </select>
                    </div>

                    <div class="col-lg-4 ">
                        <input type="file" class="form-control " id="inputEmail1">
                    </div>

                    <div class="col-lg-2">
                        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-open"></span> Upload</button>
                    </div>
                </div>

                <hr>
                <div class="form-group">
                    <div class="col-lg-offset-3 col-lg-9">
                        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-plus"></span> Voice</button>
                    </div>
                </div>-->
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-offset-3 col-lg-9">
                <button type="button" onclick="addSentences()" class="btn btn-default"><span class="glyphicon glyphicon-plus"></span> Sentence</button>
            </div>
        </div>

        <hr>
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group">
                    <label for="meaningEN" class="col-lg-3 control-label">English Meaning</label>
                    <div class="col-lg-7">
                        <input type="hidden" value="<?php echo $data['MeaningEN']->MeaningId; ?>" name="id-meaningEN" />
                        <textarea id="meaningEN" name="meaningEN" class="form-control"><?php echo $data['MeaningEN']->Meaning; ?></textarea>
                    </div>
                    <div class="col-lg-2">
                        <button type="button" class="btn <?php echo ($data['MeaningEN']->IsApproved) ? 'btn-success' : 'btn-default' ?>"
                                onclick="approveMeaning(<?php echo $data['MeaningEN']->MeaningId; ?>, 'EN')" id="btnMeaning<?php echo $data['MeaningEN']->MeaningId; ?>">
                            <span class="glyphicon glyphicon-ok"></span>
                        </button>
                    </div>
                    <?php
                    $nApprovedEN = $nApprovedEN + (($data['MeaningEN']->IsApproved) ? 1 : 0);
                    $nTotalEN++;
                    ?>
                </div>
            </div>
        </div>
    </div>
    <!-- end tab EN content -->

    <!-- tab VI content -->
    <div class="tab-pane" id="vn">
        <div class="panel panel-default">
            <div class="panel-body">
                <div id="sentencesVI">
                <?php $nApprovedVI = 0; $nTotalVI = 0; ?>
                <?php $i=1; foreach($data['SentenceVI'] as $sentence) : ?>
                <?php $nApprovedVI = $nApprovedVI + (($sentence->IsApproved) ? 1 : 0); ?>
                    <div class="form-group" id="sentenceVI-<?php echo $i; ?>">
                        <input type="hidden" name="id-sentencesVI[]" value="<?php echo $sentence->SentenceId; ?>">
                        <label for="sentenceVI-<?php echo $i; ?>" class="col-lg-3 control-label">Sentence #<?php echo $i; ?></label>
                        <div class="col-lg-7">
                            <input type="text" name="content-sentencesVI[]" class="form-control" id="sentenceVI-<?php echo $i; ?>" value="<?php echo $sentence->Sentence; ?>">
                        </div>
                        <div class="col-lg-2">
                            <button type="button" class="btn <?php echo ($sentence->IsApproved) ? 'btn-success' : 'btn-default' ?>"
                                onclick="approveSentence(<?php echo $sentence->SentenceId; ?>, 'VI')" id="btnSentence<?php echo $sentence->SentenceId; ?>">
                                <span class="glyphicon glyphicon-ok"></span>
                            </button>
                            <?php if($i > 1): ?>
                            <button type="button" class="btn btn-default" onclick="ajaxDeleteSentence(<?php echo $i; ?>, <?php echo $sentence->SentenceId; ?>)">
                                <span class="glyphicon glyphicon-remove"></span>
                            </button>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php $i++; endforeach; $nTotalVI=$i-1;?>
                </div>

                <!--<div class="form-group">
                    <label for="inputEmail1" class="col-lg-3 control-label">US, Male</label>
                    <div class="col-lg-9">
                        <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-volume-up"></span></button>
                        <button type="button" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span></button>
                        <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-remove"></span></button>
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputEmail1" class="col-lg-3 control-label">Voice File</label>
                    <div class="col-lg-3 ">
                        <select class="form-control ">
                            <option>US, Male</option>
                            <option>US, Female</option>
                        </select>
                    </div>

                    <div class="col-lg-4 ">
                        <input type="file" class="form-control " id="inputEmail1">
                    </div>

                    <div class="col-lg-2">
                        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-open"></span> Upload</button>
                    </div>
                </div>

                <hr>
                <div class="form-group">
                    <div class="col-lg-offset-3 col-lg-9">
                        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-plus"></span> Voice</button>
                    </div>
                </div>-->
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-offset-3 col-lg-9">
                <button type="button" onclick="addSentences()" class="btn btn-default"><span class="glyphicon glyphicon-plus"></span> Sentence</button>
            </div>
        </div>

        <hr>
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group">
                    <label for="inputPassword1" class="col-lg-3 control-label">Vietnamese Meaning</label>
                    <div class="col-lg-7">
                        <input type="hidden" value="<?php echo $data['MeaningVI']->MeaningId; ?>" name="id-meaningVI" />
                        <textarea name="meaningVI" id="meaningVI" class="form-control"><?php echo $data['MeaningVI']->Meaning; ?></textarea>
                    </div>
                    <div class="col-lg-2">
                        <button type="button" class="btn <?php echo ($data['MeaningVI']->IsApproved) ? 'btn-success' : 'btn-default' ?>"
                                onclick="approveMeaning(<?php echo $data['MeaningVI']->MeaningId; ?>, 'VI')" id="btnMeaning<?php echo $data['MeaningVI']->MeaningId; ?>">
                            <span class="glyphicon glyphicon-ok"></span>
                        </button>
                    </div>
                    <?php
                    $nApprovedVI = $nApprovedVI + (($data['MeaningVI']->IsApproved) ? 1 : 0);
                    $nTotalVI++;
                    ?>
                </div>
            </div>
        </div>
    </div>
    <!-- end tab VI content -->
</div>

<!-- save , clear button -->
<div class="form-group">
    <div class="col-lg-offset-3 col-lg-9">
        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-disk"></span> Save</button>
        <button type="reset" class="btn btn-default">Clear</button>
    </div>
</div>


<script>
    $('#myTab a').click(function (e) {
        e.preventDefault()
        $(this).tab('show')
    });

    var nApprovedEN = <?php echo $nApprovedEN; ?>;
    var nTotalEN = <?php echo $nTotalEN; ?>;
    var nApprovedVI = <?php echo $nApprovedVI; ?>;
    var nTotalVI = <?php echo $nTotalVI; ?>;
    var nSentence = <?php echo $data['SentenceEN']->count(); ?>;

    $('#tabEN').html('English (' + nApprovedEN + '/' + nTotalEN + ')');
    $('#tabVI').html('Vietnamese (' + nApprovedVI + '/' + nTotalVI + ')');

    function addSentences() {
        nSentence = nSentence + 1;
        $html = '<div class="form-group" id="sentenceVI-' + nSentence +'">' +
            '<input type="hidden" name="id-sentencesVI[]" value="">' +
            '<label for="sentenceVI-' + nSentence + '" class="col-lg-3 control-label">Sentence #' + nSentence + '</label>' +
            '<div class="col-lg-7">' +
            '<input type="text" name="content-sentencesVI[]" class="form-control" id="sentenceVI-' + nSentence + '" value="">' +
            '</div>' +
            '<div class="col-lg-2">' +
            '<button type="button" class="btn  btn-default" disabled="disabled"><span class="glyphicon glyphicon-ok"></span></button>' +
            '<button type="button" onclick="deleteSentence(' + nSentence + ')" class="btn  btn-default "><span class="glyphicon glyphicon-remove"></span></button>' +
            '</div>' +
            '</div>';

        $('#sentencesVI').append($html);

        $html = '<div class="form-group" id="sentenceEN-' + nSentence +'">' +
            '<input type="hidden" name="id-sentencesEN[]" value="">' +
            '<label for="sentenceEN-' + nSentence + '" class="col-lg-3 control-label">Sentence #' + nSentence + '</label>' +
            '<div class="col-lg-7">' +
            '<input type="text" name="content-sentencesEN[]" class="form-control" id="sentenceEN-' + nSentence + '" value="">' +
            '</div>' +
            '<div class="col-lg-2">' +
            '<button type="button" class="btn btn-default" disabled="disabled"><span class="glyphicon glyphicon-ok"></span></button>' +
            '<button type="button" onclick="deleteSentence(' + nSentence + ')" class="btn  btn-default "><span class="glyphicon glyphicon-remove"></span></button>' +
            '</div>' +
            '</div>';

        $('#sentencesEN').append($html);
    }

    function deleteSentence(nSentence) {
        $('#sentenceVI-' + nSentence).remove();
        $('#sentenceEN-' + nSentence).remove();
    }

    function ajaxDeleteSentence(nSentence, sentenceId) {
        if (confirm("Are you sure delete?")) {
            var objEN = $('#sentenceEN-' + nSentence);
            var btnEN = $(objEN).find('[id^="btnSentence"]')[0];
            if($(btnEN).attr('class').indexOf('btn-default') >= 0) {
                nTotalEN--;
            } else {
                nApprovedEN--; nTotalEN--;
            }
            $('#tabEN').html('English (' + nApprovedEN + '/' + nTotalEN + ')');
            $(objEN).remove();

            var objVI = $('#sentenceVI-' + nSentence);
            var btnVI = $(objVI).find('[id^="btnSentence"]')[0];
            if($(btnVI).attr('class').indexOf('btn-default') >= 0) {
                nTotalVI--;
            } else {
                nApprovedVI--; nTotalVI--;
            }
            $('#tabVI').html('Vietnamese (' + nApprovedVI + '/' + nTotalVI + ')');
            $(objVI).remove();

            $.ajax({url:"/sentence/delete/"+ sentenceId,success:function(result){

            }});
        }
    }

    function approveMeaning(meaningId, language) {
        var obj = $('#btnMeaning'+meaningId);
        var isApproved = updateButton(obj, language);

        $.ajax({url:"/meaning/approve/"+ meaningId + "/" + isApproved,success:function(result){

        }});
    }

    function approveSentence(sentenceId, language) {
        var obj = $('#btnSentence'+sentenceId);
        var isApproved = updateButton(obj, language);

        $.ajax({url:"/sentence/approve/"+ sentenceId + "/" + isApproved,success:function(result){

        }});
    }

    function updateButton(obj, language) {
        var strClass = $(obj).attr('class');
        var isApproved = 0;
        if(strClass.indexOf('btn-default') >= 0) {
            if (language == 'EN') nApprovedEN++;
            if (language == 'VI') nApprovedVI++;
            $(obj).attr('class', 'btn btn-success');
            isApproved = 1;
        } else {
            if (language == 'EN') nApprovedEN--;
            if (language == 'VI') nApprovedVI--;
            $(obj).attr('class', 'btn btn-default');
            isApproved = 0;
        }

        $('#tabEN').html('English (' + nApprovedEN + '/' + nTotalEN + ')');
        $('#tabVI').html('Vietnamese (' + nApprovedVI + '/' + nTotalVI + ')');
        return isApproved;
    }
</script>
