<input type="hidden" value="<?php echo $data['Word']->WordId; ?>" name="wordId" />
<div class="panel panel-default">
    <div class="panel-body">
        <div class="form-group">
            <label for="txtWord" class="col-lg-3 control-label">Word</label>
            <div class="col-lg-7">
                <input type="text" class="form-control input-lg" id="txtWord" name="txtWord" value="<?php echo $data['Word']->Word; ?>">
            </div>
        </div>
        <div class="form-group">
            <label for="txtTags" class="col-lg-3 control-label">Tags</label>
            <div class="col-lg-7">
                <input type="text" class="form-control" id="txtTags" name="txtTags" value="<?php echo $data['TagName']; ?>">
            </div>
        </div>
        <div class="form-group">
            <label for="isToeic" class="col-lg-3 control-label">TOEIC Word</label>
            <div class="col-lg-7">
                <input type="checkbox" id="isToeic" name="isToeic" <?php echo ($data['Word']->IsToeic)? 'checked="true"' : ''; ?>>
            </div>
        </div>

        <!--<div class="form-group">
            <label for="inputEmail1" class="col-lg-3 control-label">US, Male</label>
            <div class="col-lg-9">
                <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-volume-up"></span></button>
                <button type="button" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span></button>
                <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-remove"></span></button>
            </div>
        </div>

        <div class="form-group">
            <label for="inputEmail1" class="col-lg-3 control-label">Voice File</label>
            <div class="col-lg-3 ">
                <select class="form-control ">
                    <option>US, Male</option>
                    <option>US, Female</option>
                </select>
            </div>

            <div class="col-lg-4 ">
                <input type="file" class="form-control " id="inputEmail1">
            </div>

            <div class="col-lg-2">
                <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-open"></span> Upload</button>
            </div>
        </div>

        <hr>
        <div class="form-group">
            <div class="col-lg-offset-3 col-lg-9">
                <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-plus"></span> Voice</button>
            </div>
        </div>-->
    </div>
</div>

<ul class="nav nav-tabs" id="myTab">
    <li class="active"><a href="#en" id="tabEN">English (5/6)</a></li>
    <li class=""><a href="#vn" id="tabVI">Vietnamese (3/6)</a></li>
</ul>

<br>
<div class="tab-content">
    <!-- tab EN content -->
    <div class="tab-pane active" id="en">
        <div class="panel panel-default">
            <div class="panel-body">
                <input type="hidden" name="txtDeleteSentence" id="delete-sentence" value="">
                <div id="sentencesEN">
                    <?php $nApprovedEN = 0; $nTotalEN = 0; ?>
                    <?php $i=1; foreach($data['SentenceEN'] as $sentence) : ?>
                    <?php $nApprovedEN = $nApprovedEN + (($sentence->IsApproved) ? 1 : 0); ?>
                    <div class="form-group" id="sentenceEN-<?php echo $i; ?>">
                        <input type="hidden" name="id-sentencesEN[]" value="<?php echo $sentence->SentenceId; ?>">
                        <label for="sentenceEN-<?php echo $i; ?>" class="col-lg-3 control-label">Sentence #<?php echo $i; ?></label>
                        <div class="col-lg-7">
                            <input type="text" name="content-sentencesEN[]" class="form-control" id="sentenceEN-<?php echo $i; ?>" value="<?php echo $sentence->Sentence; ?>" <?php echo ($sentence->IsApproved) ? 'readonly="readonly"' : '';?>>
                            <input type="hidden" name="approve-sentenceEN[]" id="approveSentenceEN-<?php echo $i; ?>" value="<?php echo $sentence->IsApproved; ?>">
                        </div>
                        <div class="col-lg-2">
                            <button type="button" class="btn <?php echo ($sentence->IsApproved) ? 'btn-success' : 'btn-default' ?>"
                                    onclick="approveSentence(<?php echo $i; ?>, 'EN')" id="btnSentenceEN<?php echo $i; ?>">
                                <span class="glyphicon glyphicon-ok"></span>
                            </button>
                            <?php if($i > 1): ?>
                            <button type="button" class="btn btn-default" onclick="deleteSentence(<?php echo $i; ?>, <?php echo $sentence->SentenceId; ?>)">
                                <span class="glyphicon glyphicon-remove"></span>
                            </button>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php $i++; endforeach; $nTotalEN=$i-1;?>
                </div>

                <!--<div class="form-group">
                    <label for="inputEmail1" class="col-lg-3 control-label">US, Male</label>
                    <div class="col-lg-9">
                        <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-volume-up"></span></button>
                        <button type="button" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span></button>
                        <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-remove"></span></button>
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputEmail1" class="col-lg-3 control-label">Voice File</label>
                    <div class="col-lg-3 ">
                        <select class="form-control ">
                            <option>US, Male</option>
                            <option>US, Female</option>
                        </select>
                    </div>

                    <div class="col-lg-4 ">
                        <input type="file" class="form-control " id="inputEmail1">
                    </div>

                    <div class="col-lg-2">
                        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-open"></span> Upload</button>
                    </div>
                </div>

                <hr>
                <div class="form-group">
                    <div class="col-lg-offset-3 col-lg-9">
                        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-plus"></span> Voice</button>
                    </div>
                </div>-->
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-offset-3 col-lg-9">
                <button type="button" onclick="addSentences()" class="btn btn-default"><span class="glyphicon glyphicon-plus"></span> Sentence</button>
            </div>
        </div>

        <hr>
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group">
                    <label for="meaningEN" class="col-lg-3 control-label">English Meaning</label>
                    <div class="col-lg-7">
                        <input type="hidden" value="<?php echo $data['MeaningEN']->MeaningId; ?>" name="id-meaningEN" />
                        <textarea id="meaningEN" name="meaningEN" class="form-control" <?php echo ($data['MeaningEN']->IsApproved) ? 'readonly="readonly"' : '';?>><?php echo $data['MeaningEN']->Meaning; ?></textarea>
                        <input type="hidden" name="approve-meaningEN" id="approve-meaningEN" value="<?php echo $data['MeaningEN']->IsApproved; ?>">
                    </div>
                    <div class="col-lg-2">
                        <button type="button" class="btn <?php echo ($data['MeaningEN']->IsApproved) ? 'btn-success' : 'btn-default' ?>"
                                onclick="approveMeaning(<?php echo $data['MeaningEN']->MeaningId; ?>, 'EN')" id="btnMeaning<?php echo $data['MeaningEN']->MeaningId; ?>">
                            <span class="glyphicon glyphicon-ok"></span>
                        </button>
                    </div>
                    <?php
                    $nApprovedEN = $nApprovedEN + (($data['MeaningEN']->IsApproved) ? 1 : 0);
                    $nTotalEN++;
                    ?>
                </div>
            </div>
        </div>
    </div>
    <!-- end tab EN content -->

    <!-- tab VI content -->
    <div class="tab-pane" id="vn">
        <div class="panel panel-default">
            <div class="panel-body">
                <div id="sentencesVI">
                <?php $nApprovedVI = 0; $nTotalVI = 0; ?>
                <?php $i=1; foreach($data['SentenceVI'] as $sentence) : ?>
                <?php $nApprovedVI = $nApprovedVI + (($sentence->IsApproved) ? 1 : 0); ?>
                    <div class="form-group" id="sentenceVI-<?php echo $i; ?>">
                        <input type="hidden" name="id-sentencesVI[]" value="<?php echo $sentence->SentenceId; ?>">
                        <label for="sentenceVI-<?php echo $i; ?>" class="col-lg-3 control-label">Sentence #<?php echo $i; ?></label>
                        <div class="col-lg-7">
                            <input type="text" name="content-sentencesVI[]" class="form-control" id="sentenceVI-<?php echo $i; ?>" value="<?php echo $sentence->Sentence; ?>" <?php echo ($sentence->IsApproved) ? 'readonly="readonly"' : '';?>>
                            <input type="hidden" name="approve-sentenceVI[]" id="approveSentenceVI-<?php echo $i; ?>" value="<?php echo $sentence->IsApproved; ?>">
                        </div>
                        <div class="col-lg-2">
                            <button type="button" class="btn <?php echo ($sentence->IsApproved) ? 'btn-success' : 'btn-default' ?>"
                                onclick="approveSentence(<?php echo $i; ?>, 'VI')" id="btnSentenceVI<?php echo $i; ?>">
                                <span class="glyphicon glyphicon-ok"></span>
                            </button>
                            <?php if($i > 1): ?>
                            <button type="button" class="btn btn-default" onclick="deleteSentence(<?php echo $i; ?>, <?php echo $sentence->SentenceId; ?>)">
                                <span class="glyphicon glyphicon-remove"></span>
                            </button>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php $i++; endforeach; $nTotalVI=$i-1;?>
                </div>

                <!--<div class="form-group">
                    <label for="inputEmail1" class="col-lg-3 control-label">US, Male</label>
                    <div class="col-lg-9">
                        <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-volume-up"></span></button>
                        <button type="button" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span></button>
                        <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-remove"></span></button>
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputEmail1" class="col-lg-3 control-label">Voice File</label>
                    <div class="col-lg-3 ">
                        <select class="form-control ">
                            <option>US, Male</option>
                            <option>US, Female</option>
                        </select>
                    </div>

                    <div class="col-lg-4 ">
                        <input type="file" class="form-control " id="inputEmail1">
                    </div>

                    <div class="col-lg-2">
                        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-open"></span> Upload</button>
                    </div>
                </div>

                <hr>
                <div class="form-group">
                    <div class="col-lg-offset-3 col-lg-9">
                        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-plus"></span> Voice</button>
                    </div>
                </div>-->
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-offset-3 col-lg-9">
                <button type="button" onclick="addSentences()" class="btn btn-default"><span class="glyphicon glyphicon-plus"></span> Sentence</button>
            </div>
        </div>

        <hr>
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group">
                    <label for="inputPassword1" class="col-lg-3 control-label">Vietnamese Meaning</label>
                    <div class="col-lg-7">
                        <input type="hidden" value="<?php echo $data['MeaningVI']->MeaningId; ?>" name="id-meaningVI" />
                        <textarea name="meaningVI" id="meaningVI" class="form-control" <?php echo ($data['MeaningVI']->IsApproved) ? 'readonly="readonly"' : '';?>><?php echo $data['MeaningVI']->Meaning; ?></textarea>
                        <input type="hidden" name="approve-meaningVI" id="approve-meaningVI" value="<?php echo $data['MeaningVI']->IsApproved; ?>">
                    </div>
                    <div class="col-lg-2">
                        <button type="button" class="btn <?php echo ($data['MeaningVI']->IsApproved) ? 'btn-success' : 'btn-default' ?>"
                                onclick="approveMeaning(<?php echo $data['MeaningVI']->MeaningId; ?>, 'VI')" id="btnMeaning<?php echo $data['MeaningVI']->MeaningId; ?>">
                            <span class="glyphicon glyphicon-ok"></span>
                        </button>
                    </div>
                    <?php
                    $nApprovedVI = $nApprovedVI + (($data['MeaningVI']->IsApproved) ? 1 : 0);
                    $nTotalVI++;
                    ?>
                </div>
            </div>
        </div>
    </div>
    <!-- end tab VI content -->
</div>

<!-- save , clear button -->
<div class="form-group">
    <div class="col-lg-offset-3 col-lg-9">
        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-disk"></span> Save</button>
        <button type="reset" class="btn btn-default">Clear</button>
    </div>
</div>


<script>
    var nApprovedEN = <?php echo $nApprovedEN; ?>;
    var nTotalEN = <?php echo $nTotalEN; ?>;
    var nApprovedVI = <?php echo $nApprovedVI; ?>;
    var nTotalVI = <?php echo $nTotalVI; ?>;
    var nSentence = <?php echo $data['SentenceEN']->count(); ?>;
    var nSentenceReal = nSentence;
</script>
<script type="text/javascript" src="/js/editform.js"></script>
