<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/css/showloading.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-tagsinput.css')
        ->prependStylesheet($this->basePath() . '/css/app.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/general.js')
        ->prependFile($this->basePath() . '/js/jquery.fastLiveFilter.js')
        ->prependFile($this->basePath() . '/js/jquery.showloading.min.js')
        ->prependFile($this->basePath() . '/js/bootstrap-tagsinput.min.js')
        ->prependFile($this->basePath() . '/js/typeahead.min.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

</head>
<body>
<!-- HEADER MENU -->
<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container">
        <?php $params = $this->myViewHelper()->getAllParams(); ?>
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Travel Dream</a> </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="<?php echo ($params['controller'] == 'Application\Controller\AddWord' && strtolower($params['action']) == 'index')  ? 'active' : ''; ?>">
                    <a href="<?php echo $this->url('application/default', array('controller'=>'add-word'));?>">
                        <span class="glyphicon glyphicon-plus-sign"></span> Add Word</a></li>
                <li class="<?php echo ($params['controller'] == 'Application\Controller\Library' && strtolower($params['action']) == 'show-list' && strtoupper($params['status']) == 'NEED CONTENT')  ? 'active' : ''; ?>">
                    <a href="<?php echo $this->url('application/library', array('action'=>'show-list', 'status' => 'NEED CONTENT'));?>">
                        <span class="glyphicon glyphicon-remove-circle"></span> Need Content</a></li>
                <li class="<?php echo ($params['controller'] == 'Application\Controller\Library' && strtolower($params['action']) == 'show-list' && strtoupper($params['status']) == 'WAITING APPROVE CONTENT')  ? 'active' : ''; ?>">
                    <a href="<?php echo $this->url('application/library', array('action'=>'show-list', 'status' => 'WAITING APPROVE CONTENT'));?>">
                        <span class="glyphicon glyphicon-time"></span> Waiting Approve Content</a></li>
                <li class="<?php echo ($params['controller'] == 'Application\Controller\Library' && strtolower($params['action']) == 'show-list' && strtoupper($params['status']) == 'NEED SOUND')  ? 'active' : ''; ?>">
                    <a href="<?php echo $this->url('application/library', array('action'=>'show-list', 'status' => 'NEED SOUND'));?>">
                        <span class="glyphicon glyphicon-headphones"></span> Need Sound</a></li>
                <li class="<?php echo ($params['controller'] == 'Application\Controller\Library' && strtolower($params['action']) == 'show-list' && strtoupper($params['status']) == 'WAITING APPROVE SOUND')  ? 'active' : ''; ?>">
                    <a href="<?php echo $this->url('application/library', array('action'=>'show-list', 'status' => 'WAITING APPROVE SOUND'));?>">
                        <span class="glyphicon glyphicon-import"></span> Waiting Approve Sound</a></li>
                <li class="<?php echo ($params['controller'] == 'Application\Controller\Library' && strtolower($params['action']) == 'show-list' && strtoupper($params['status']) == 'COMPLETED')  ? 'active' : ''; ?>">
                    <a href="<?php echo $this->url('application/library', array('action'=>'show-list', 'status' => 'COMPLETED'));?>">
                        <span class="glyphicon glyphicon-ok"></span> Completed</a></li>
            </ul>
        </div>
        <!-- /.nav-collapse -->
    </div>
    <!-- /.container -->
</div>
<!-- /.navbar -->


<div class="container">
    <?php echo $this->content; ?>
    <hr>
    <footer>
        <p>&copy; KiSS team 2013</p>
    </footer>
</div> <!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>
