<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/general.js')
            ->prependFile($this->basePath() . '/js/jquery.fastLiveFilter.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <!-- HEADER MENU -->
        <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
              <a class="navbar-brand" href="#">Travel Dream</a> </div>
            <div class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                <li><a href="#"><span class="glyphicon glyphicon-import"></span> New Word</a></li>
                <li class="active"><a href="#"><span class="glyphicon glyphicon-ok"></span> Completed</a></li>
                <li><a href="#"><span class="glyphicon glyphicon-headphones"></span> Need Sound</a></li>
                <li><a href="#"><span class="glyphicon glyphicon-remove-circle"></span> Require En</a></li>
                <li><a href="#"><span class="glyphicon glyphicon-remove-sign"></span> Require Vi</a></li>
                <li><a href="#"><span class="glyphicon glyphicon-time"></span> Waiting Approve</a></li>
              </ul>
            </div>
            <!-- /.nav-collapse -->
          </div>
          <!-- /.container -->
        </div>
        <!-- /.navbar -->


        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; KiSS team 2013</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
