<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <?php $this->headTitle()->setSeparator(' | '); ?>
        <?php $this->headTitle()->prepend('English Media');?>
        <?php echo $this->headTitle() ?>
        <link rel="shortcut icon" href="/images/favicon_rosa.ico?v=1" />

        <?php echo $this->headTitle() ?>
        <?php echo $this->headScript() ?>
        <?php echo $this->headStyle() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headMeta() ?>
    </head>
    <body>
        Header Page
        <div class="container">
            <div class="">
                <?php echo $this->layout()->content ?>
            </div>
        </div>
        Footer Page
    </body>
</html>